version: "3.9"
services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "0.0.0.0:33371:8080"
    environment:
      - OPENAI_API_KEY=dummy
      - OPENAI_API_BASE_URL=http://litellm:4000/v1
    volumes:
      - open-webui:/app/backend/data
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    command: ["--config=/litellm_config.yaml", "--detailed_debug"]
    ports:
      - "0.0.0.0:33372:4000"
    environment:
      - LITELLM_MASTER_KEY=dummy
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./litellm_config.yaml:/litellm_config.yaml
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "0.0.0.0:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
volumes:
  open-webui:
  ollama_data:
