model_list:
  - model_name: grok
    litellm_params:
      model: xai/grok-2-latest
      api_key: ${XAI_API_KEY}
  - model_name: gemini-1.5-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      api_key: ${GEMINI_API_KEY}
      vertex_project: ${VERTEXAI_PROJECT}
      vertex_location: us-central1
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: ${OPENAI_API_KEY}
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: ${ANTHROPIC_API_KEY}
  - model_name: copilot-gpt4
    litellm_params:
      model: azure/gpt-4
      api_key: ${AZURE_API_KEY}
      api_base: ${AZURE_API_BASE}
      api_version: ${AZURE_API_VERSION}
  - model_name: phi3
    litellm_params:
      model: ollama/phi3
      api_base: http://ollama:11434
  - model_name: gemma2
    litellm_params:
      model: ollama/gemma2:2b
      api_base: http://ollama:11434
general_settings:
  enable_cache: true
